apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "bind-exporter"
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          # Mantém apenas o container bind-exporter
          - source_labels: [__meta_kubernetes_pod_container_name]
            regex: bind-exporter
            action: keep

          # Mantém apenas a porta do exporter
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9119"
            action: keep
